package spec

import (
	"fmt"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
)

//Main API Object
type ZookeeperCluster struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata"`
	//Metadata          metav1.ObjectMeta `json:"metadata"`

	Spec  ZookeeperClusterSpec  `json:"spec"`
	State ZookeeperClusterState `json:"state,omitempty"`
	Scale ZookeeperClusterScale `json:"scale,omitempty"`
}

// k8s API List Type
type ZookeeperClusterList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata"`
	//Metadata        metav1.ListMeta `json:"metadata"`

	Items []ZookeeperCluster `json:"items"`
}

type ZookeeperClusterSpec struct {
}

type ZookeeperClusterState struct {
}

type ZookeeperClusterScale struct {
}

type ZookeeperClusterWatchEvent struct {
	Type      string       `json:"type"`
	Object    ZookeeperCluster `json:"object"`
	OldObject ZookeeperCluster `json:"oldObject"`
}

//convenience functions
func PrintCluster(cluster *ZookeeperCluster) string {
	return fmt.Sprintf("%s/%s, APIVersion: %s, Kind: %s, Value: %#v", cluster.ObjectMeta.Namespace, cluster.ObjectMeta.Name, cluster.APIVersion, cluster.Kind, cluster)
}

// Required to satisfy Object interface
func (e *ZookeeperCluster) GetObjectKind() schema.ObjectKind {
	return &e.TypeMeta
}

// Required to satisfy Object interface
func (el *ZookeeperClusterList) GetObjectKind() schema.ObjectKind {

	return &el.TypeMeta
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZookeeperCluster) DeepCopyInto(out *ZookeeperCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	//in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.ObjectMeta = in.ObjectMeta

	out.Spec = in.Spec
	return
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, creating a new Kafkacluster.
func (x *ZookeeperCluster) DeepCopy() *ZookeeperCluster {
	if x == nil {
		return nil
	}
	out := new(ZookeeperCluster)
	x.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (x *ZookeeperCluster) DeepCopyObject() runtime.Object {
	if c := x.DeepCopy(); c != nil {
		return c
	} else {
		return nil
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZookeeperClusterList) DeepCopyInto(out *ZookeeperClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ZookeeperCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, creating a new KafkaclusterList.
func (x *ZookeeperClusterList) DeepCopy() *ZookeeperClusterList {
	if x == nil {
		return nil
	}
	out := new(ZookeeperClusterList)
	x.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (x *ZookeeperClusterList) DeepCopyObject() runtime.Object {
	if c := x.DeepCopy(); c != nil {
		return c
	} else {
		return nil
	}
}